import "server-only";
import {
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import type { PlanView } from "@/lib/db/plans";
import type { ConfigView } from "@/lib/db/configs";
import { normalizeRoadmap, fmtDate, fmtWeekRange, weekDueDate } from "@/lib/geo/schedule";

/**
 * Manager-ready Word document: per tactic/action WHAT · WHY · HOW · WHO · TIMELINE
 * (real dates derived from plan creation), plus overall execution guidelines.
 * Framing stays "modeled estimate, not a guarantee" with the assumptions listed.
 */

const MUTED = "6B7280";
const ACCENT = "7C3AED";
const WARN = "B45309";

function pct(n: number | null | undefined) {
  return n == null ? "—" : `${Math.round(n * 100)}%`;
}

function h(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]) {
  return new Paragraph({ heading: level, spacing: { before: 240, after: 120 }, children: [new TextRun(text)] });
}

function body(text: string, opts?: { muted?: boolean; bold?: boolean; color?: string }) {
  return new Paragraph({
    spacing: { after: 80 },
    children: [
      new TextRun({
        text,
        bold: opts?.bold,
        color: opts?.color ?? (opts?.muted ? MUTED : undefined),
      }),
    ],
  });
}

function labeled(label: string, text: string) {
  return new Paragraph({
    spacing: { after: 60 },
    children: [new TextRun({ text: `${label}: `, bold: true, color: ACCENT }), new TextRun({ text })],
  });
}

function bullet(text: string) {
  return new Paragraph({
    spacing: { after: 40 },
    bullet: { level: 0 },
    children: [new TextRun({ text })],
  });
}

/* Manual "1." prefixes (not docx numbering) so steps restart at 1 for every action. */
function step(text: string, n: number) {
  return new Paragraph({
    spacing: { after: 40 },
    indent: { left: 480, hanging: 240 },
    children: [new TextRun({ text: `${n}. ${text}` })],
  });
}

function cell(text: string, opts?: { bold?: boolean; widthPct?: number }) {
  return new TableCell({
    width: opts?.widthPct ? { size: opts.widthPct, type: WidthType.PERCENTAGE } : undefined,
    margins: { top: 60, bottom: 60, left: 100, right: 100 },
    children: [new Paragraph({ children: [new TextRun({ text, bold: opts?.bold })] })],
  });
}

export async function buildPlanDocx(plan: PlanView, cfg: ConfigView | null): Promise<Buffer> {
  const p = plan.projection;
  const brand = cfg?.brandName || cfg?.brandUrl || "Your brand";
  const roadmap = normalizeRoadmap(plan.roadmap);
  const created = new Date(plan.createdAt);
  const timeline = p?.timelineWeeks ?? plan.timelineWeeks ?? roadmap.weeks.length;

  const children: (Paragraph | Table)[] = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun(`GEO action plan — ${brand}`)],
    }),
    body(
      `Generated by GetCited on ${fmtDate(created)} · ${timeline}-week program · all projections are modeled estimates, not guarantees.`,
      { muted: true },
    ),

    h("Executive summary", HeadingLevel.HEADING_1),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 2, color: "DDDDDD" },
        bottom: { style: BorderStyle.SINGLE, size: 2, color: "DDDDDD" },
        left: { style: BorderStyle.SINGLE, size: 2, color: "DDDDDD" },
        right: { style: BorderStyle.SINGLE, size: 2, color: "DDDDDD" },
        insideHorizontal: { style: BorderStyle.SINGLE, size: 2, color: "DDDDDD" },
        insideVertical: { style: BorderStyle.SINGLE, size: 2, color: "DDDDDD" },
      },
      rows: [
        ["Current AI citation share", pct(p?.currentCitationShare)],
        ["Projected citation share (modeled)", `${pct(p?.targetCitationShare)} in ~${timeline} weeks`],
        ["Confidence", p?.confidence ?? "low"],
        ["Extra AI sessions / month (modeled)", `≈ +${(p?.projectedTrafficUplift ?? 0).toLocaleString()}`],
        ["Extra conversions / month (modeled)", `≈ +${(p?.projectedConversions ?? 0).toLocaleString()}`],
        ["Tactics in plan", String(plan.tactics.length)],
        ["Program window", `${fmtDate(created)} → ${fmtDate(weekDueDate(created, timeline || 1))}`],
      ].map(
        ([k, v]) =>
          new TableRow({ children: [cell(k!, { bold: true, widthPct: 55 }), cell(v!, { widthPct: 45 })] }),
      ),
    }),
  ];

  if (roadmap.guidelines.length) {
    children.push(h("How to run this plan (execution guidelines)", HeadingLevel.HEADING_1));
    for (const g of roadmap.guidelines) children.push(bullet(g));
  }

  children.push(h("Tactic overview", HeadingLevel.HEADING_1));
  children.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          children: [
            cell("Tactic", { bold: true, widthPct: 42 }),
            cell("Closes gap", { bold: true, widthPct: 18 }),
            cell("Cost", { bold: true, widthPct: 12 }),
            cell("Effort", { bold: true, widthPct: 12 }),
            cell("Lead time", { bold: true, widthPct: 16 }),
          ],
        }),
        ...plan.tactics.map(
          (t) =>
            new TableRow({
              children: [
                cell(t.name),
                cell(t.closesGap ?? "—"),
                cell(t.costUsd === 0 ? "free" : `$${t.costUsd.toFixed(0)}`),
                cell(`${Math.round(t.effortHours)}h`),
                cell(`${t.leadWeeks[0]}–${t.leadWeeks[1]} wk`),
              ],
            }),
        ),
      ],
    }),
  );

  if (roadmap.weeks.length) {
    children.push(h("Week-by-week roadmap", HeadingLevel.HEADING_1));
    children.push(
      body(
        "Every action states WHAT to do, WHY (the citation gap it closes), HOW (step-by-step), WHO owns it, and its TIMELINE. Dates run from the plan creation date.",
        { muted: true },
      ),
    );
    for (const w of roadmap.weeks) {
      children.push(
        h(`Week ${w.week} · ${fmtWeekRange(created, w.week)} — ${w.theme}`, HeadingLevel.HEADING_2),
      );
      for (const a of w.actions) {
        children.push(
          new Paragraph({
            spacing: { before: 120, after: 60 },
            children: [new TextRun({ text: a.action, bold: true })],
          }),
        );
        if (a.why) children.push(labeled("Why", a.why));
        children.push(
          labeled(
            "Who / effort",
            `${a.owner_role} · ~${Math.round(a.hours)}h · due ${fmtDate(weekDueDate(created, w.week))}`,
          ),
        );
        children.push(labeled("Deliverable", a.deliverable));
        if (a.how?.length) {
          children.push(body("How:", { bold: true }));
          a.how.forEach((s, i) => children.push(step(s, i + 1)));
        }
      }
      children.push(body(`KPI checkpoint: ${w.kpi_checkpoint}`, { color: WARN }));
    }
  }

  children.push(h("Assumptions & framing", HeadingLevel.HEADING_1));
  children.push(
    body(
      p?.disclaimer ??
        "This projection is a modeled estimate based on the assumptions below — it is not a guarantee.",
      { color: WARN },
    ),
  );
  for (const a of p?.assumptions ?? []) children.push(bullet(a));

  const doc = new Document({
    creator: "GetCited",
    title: `GEO action plan — ${brand}`,
    sections: [{ children }],
  });
  return Packer.toBuffer(doc);
}
