import "server-only";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { PlanView } from "@/lib/db/plans";
import type { ConfigView } from "@/lib/db/configs";
import type { RoadmapWeek } from "@/lib/geo/roadmap";

function pct(n: number | null | undefined) {
  return n == null ? "—" : `${Math.round(n * 100)}%`;
}

function roadmapOf(plan: PlanView): RoadmapWeek[] {
  return Array.isArray(plan.roadmap) ? (plan.roadmap as RoadmapWeek[]) : [];
}

const s = StyleSheet.create({
  page: { backgroundColor: "#0B0D10", color: "#E6E8EB", padding: 36, fontSize: 10 },
  h1: { fontSize: 20, marginBottom: 2 },
  sub: { color: "#8A9099", marginBottom: 18, fontSize: 10 },
  card: { backgroundColor: "#14171C", border: "1 solid #22272F", borderRadius: 10, padding: 14, marginBottom: 12 },
  big: { fontSize: 22, color: "#635BFF" },
  row: { flexDirection: "row", justifyContent: "space-between", borderBottom: "1 solid #22272F", paddingVertical: 4 },
  th: { color: "#8A9099", fontSize: 9 },
  muted: { color: "#8A9099" },
  warn: { color: "#E0A32E" },
  li: { color: "#8A9099", fontSize: 8, marginBottom: 2 },
});

function PlanPdf({ plan, cfg }: { plan: PlanView; cfg: ConfigView | null }) {
  const p = plan.projection;
  const brand = cfg?.brandName || cfg?.brandUrl || "Your brand";
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.h1}>GEO action plan — {brand}</Text>
        <Text style={s.sub}>Costed plan + modeled projection · generated by GetCited</Text>

        <View style={s.card}>
          <Text>Projected citation share ({p?.confidence ?? "low"} confidence)</Text>
          <Text style={{ marginTop: 6 }}>
            <Text style={{ fontSize: 22 }}>{pct(p?.currentCitationShare)}</Text>
            <Text style={s.muted}> {"  ->  "} </Text>
            <Text style={s.big}>{pct(p?.targetCitationShare)}</Text>
            <Text style={s.muted}> in ~{p?.timelineWeeks ?? plan.timelineWeeks} weeks</Text>
          </Text>
          <Text style={{ marginTop: 6 }}>
            ≈ +{(p?.projectedTrafficUplift ?? 0).toLocaleString()} AI sessions/mo · ≈ +
            {(p?.projectedConversions ?? 0).toLocaleString()} conversions/mo
          </Text>
        </View>

        <View style={s.card}>
          <Text style={{ marginBottom: 6 }}>Plan · {plan.tactics.length} tactics</Text>
          <View style={s.row}>
            <Text style={[s.th, { width: "50%" }]}>Tactic</Text>
            <Text style={[s.th, { width: "20%" }]}>Closes gap</Text>
            <Text style={[s.th, { width: "15%", textAlign: "right" }]}>Cost</Text>
            <Text style={[s.th, { width: "15%", textAlign: "right" }]}>Effort</Text>
          </View>
          {plan.tactics.map((t) => (
            <View style={s.row} key={t.id}>
              <Text style={{ width: "50%" }}>{t.name}</Text>
              <Text style={[s.muted, { width: "20%" }]}>{t.closesGap ?? "—"}</Text>
              <Text style={[s.muted, { width: "15%", textAlign: "right" }]}>
                {t.costUsd === 0 ? "free" : `$${t.costUsd.toFixed(0)}`}
              </Text>
              <Text style={[s.muted, { width: "15%", textAlign: "right" }]}>{Math.round(t.effortHours)}h</Text>
            </View>
          ))}
        </View>

        <View style={s.card}>
          <Text style={s.warn}>Modeled projection — not a guarantee.</Text>
          <Text style={[s.muted, { marginTop: 4, fontSize: 9 }]}>{p?.disclaimer ?? ""}</Text>
          <Text style={{ marginTop: 6, fontSize: 9 }}>Assumptions:</Text>
          {(p?.assumptions ?? []).map((a, i) => (
            <Text style={s.li} key={i}>
              • {a}
            </Text>
          ))}
        </View>
      </Page>

      {roadmapOf(plan).length > 0 && (
        <Page size="A4" style={s.page}>
          <Text style={s.h1}>Week-by-week roadmap</Text>
          <Text style={s.sub}>
            Hand this to the team: every action has an owner role, hours and a deliverable.
          </Text>
          {roadmapOf(plan).map((w) => (
            <View style={s.card} key={w.week} wrap={false}>
              <Text style={{ fontSize: 12, marginBottom: 4 }}>
                Week {w.week} — {w.theme}
              </Text>
              <View style={s.row}>
                <Text style={[s.th, { width: "44%" }]}>Action</Text>
                <Text style={[s.th, { width: "18%" }]}>Owner</Text>
                <Text style={[s.th, { width: "8%", textAlign: "right" }]}>Hrs</Text>
                <Text style={[s.th, { width: "30%" }]}>Deliverable</Text>
              </View>
              {w.actions.map((a, i) => (
                <View style={s.row} key={i}>
                  <Text style={{ width: "44%" }}>{a.action}</Text>
                  <Text style={[s.muted, { width: "18%" }]}>{a.owner_role}</Text>
                  <Text style={[s.muted, { width: "8%", textAlign: "right" }]}>{Math.round(a.hours)}</Text>
                  <Text style={[s.muted, { width: "30%" }]}>{a.deliverable}</Text>
                </View>
              ))}
              <Text style={[s.warn, { marginTop: 5, fontSize: 8 }]}>KPI checkpoint: {w.kpi_checkpoint}</Text>
            </View>
          ))}
        </Page>
      )}
    </Document>
  );
}

export async function buildPlanPdf(plan: PlanView, cfg: ConfigView | null): Promise<Buffer> {
  return renderToBuffer(<PlanPdf plan={plan} cfg={cfg} />);
}
