import "server-only";
import ExcelJS from "exceljs";
import type { PlanView } from "@/lib/db/plans";
import type { ConfigView } from "@/lib/db/configs";

function pct(n: number | null | undefined) {
  return n == null ? "—" : `${Math.round(n * 100)}%`;
}
function esc(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Self-contained, interactive-ish HTML report (dark, matches the app). */
export function buildPlanHtml(plan: PlanView, cfg: ConfigView | null): string {
  const p = plan.projection;
  const brand = cfg?.brandName || cfg?.brandUrl || "Your brand";
  const tacticRows = plan.tactics
    .map(
      (t) => `<tr>
        <td>${esc(t.name)}</td>
        <td>${t.closesGap ? esc(t.closesGap) : "—"}</td>
        <td class="num">${t.costUsd === 0 ? "free" : "$" + t.costUsd.toFixed(0)}</td>
        <td class="num">${Math.round(t.effortHours)}h</td>
        <td class="num">${t.leadWeeks[0]}–${t.leadWeeks[1]} wk</td>
      </tr>`,
    )
    .join("");
  const assumptions = (p?.assumptions ?? []).map((a) => `<li>${esc(a)}</li>`).join("");

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>GetCited plan — ${esc(brand)}</title>
<style>
:root{--bg:#0B0D10;--card:#14171C;--accent:#635BFF;--pos:#2FBF71;--warn:#E0A32E;--text:#E6E8EB;--muted:#8A9099;--border:#22272F}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 Inter,system-ui,sans-serif;padding:32px}
.wrap{max-width:820px;margin:0 auto}h1{font-size:26px;margin:0 0 4px}.sub{color:var(--muted);margin:0 0 24px}
.card{background:var(--card);border:1px solid var(--border);border-radius:16px;padding:20px;margin-bottom:16px}
.big{font-size:30px;font-weight:600}.accent{color:var(--accent)}.muted{color:var(--muted)}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.kpi{background:#0f1216;border:1px solid var(--border);border-radius:12px;padding:12px}
table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--border)}
th{color:var(--muted);font-weight:500}.num{text-align:right;color:var(--muted)}
.badge{display:inline-block;border-radius:999px;padding:2px 10px;font-size:11px;text-transform:uppercase;border:1px solid}
.badge.high{color:var(--pos);border-color:var(--pos)}.badge.medium{color:var(--warn);border-color:var(--warn)}.badge.low{color:#E5484D;border-color:#E5484D}
.warn{background:rgba(224,163,46,.08);border:1px solid rgba(224,163,46,.25);border-radius:12px;padding:14px;font-size:13px;color:var(--muted)}
ul{margin:8px 0 0;padding-left:18px}li{margin:3px 0;font-size:12px;color:var(--muted)}
</style></head><body><div class="wrap">
<h1>GEO action plan — <span class="accent">${esc(brand)}</span></h1>
<p class="sub">Costed plan + modeled projection · generated by GetCited</p>

<div class="card">
  <div style="display:flex;align-items:center;gap:8px">
    <strong>Projected citation share</strong>
    <span class="badge ${p?.confidence ?? "low"}" style="margin-left:auto">${p?.confidence ?? "low"} confidence</span>
  </div>
  <div style="margin:10px 0"><span class="big">${pct(p?.currentCitationShare)}</span>
    <span class="muted"> → </span><span class="big accent">${pct(p?.targetCitationShare)}</span>
    <span class="muted"> in ~${p?.timelineWeeks ?? plan.timelineWeeks} weeks</span></div>
  <div class="grid">
    <div class="kpi"><div class="muted" style="font-size:12px">Extra AI sessions / mo</div><div style="font-weight:600">≈ +${(p?.projectedTrafficUplift ?? 0).toLocaleString()}</div></div>
    <div class="kpi"><div class="muted" style="font-size:12px">Extra conversions / mo</div><div style="font-weight:600">≈ +${(p?.projectedConversions ?? 0).toLocaleString()}</div></div>
  </div>
</div>

<div class="card">
  <strong>Plan · ${plan.tactics.length} tactics</strong>
  <table style="margin-top:10px"><thead><tr><th>Tactic</th><th>Closes gap</th><th class="num">Cost</th><th class="num">Effort</th><th class="num">Lead</th></tr></thead>
  <tbody>${tacticRows}</tbody></table>
</div>

<div class="warn">
  <strong style="color:var(--warn)">Modeled projection — not a guarantee.</strong>
  <p style="margin:6px 0 0">${esc(p?.disclaimer ?? "")}</p>
  <details style="margin-top:8px"><summary style="cursor:pointer;color:var(--warn);font-size:12px">Assumptions (${p?.assumptions?.length ?? 0})</summary>
  <ul>${assumptions}</ul></details>
</div>
</div></body></html>`;
}

/** Excel workbook: Projection + Tactics + Assumptions sheets. */
export async function buildPlanWorkbook(plan: PlanView, cfg: ConfigView | null): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "GetCited";
  const p = plan.projection;

  const proj = wb.addWorksheet("Projection");
  proj.columns = [{ header: "Metric", width: 34 }, { header: "Value", width: 24 }];
  proj.addRows([
    ["Brand", cfg?.brandName || cfg?.brandUrl || ""],
    ["Current citation share", pct(p?.currentCitationShare)],
    ["Target citation share", pct(p?.targetCitationShare)],
    ["Projected share gain", pct(p?.projectedShareGain)],
    ["Timeline (weeks)", p?.timelineWeeks ?? plan.timelineWeeks ?? ""],
    ["Extra AI sessions / mo", p?.projectedTrafficUplift ?? 0],
    ["Extra conversions / mo", p?.projectedConversions ?? 0],
    ["Confidence", p?.confidence ?? "low"],
    ["Note", "Modeled projection, not a guarantee."],
  ]);
  proj.getRow(1).font = { bold: true };

  const tac = wb.addWorksheet("Tactics");
  tac.columns = [
    { header: "Tactic", width: 44 },
    { header: "Closes gap", width: 16 },
    { header: "Cost (USD)", width: 12 },
    { header: "Effort (hrs)", width: 12 },
    { header: "Lead (weeks)", width: 14 },
  ];
  for (const t of plan.tactics) {
    tac.addRow([t.name, t.closesGap ?? "", t.costUsd, Math.round(t.effortHours), `${t.leadWeeks[0]}-${t.leadWeeks[1]}`]);
  }
  tac.getRow(1).font = { bold: true };

  const asm = wb.addWorksheet("Assumptions");
  asm.columns = [{ header: "Assumption", width: 90 }];
  for (const a of p?.assumptions ?? []) asm.addRow([a]);
  asm.getRow(1).font = { bold: true };

  const arr = await wb.xlsx.writeBuffer();
  return Buffer.from(arr);
}
