import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {query,closeDatabase,transaction} from '../src/lib/db/client';
import {runWithExecution,type Execution} from '../src/lib/server/execution';
import {saveConfigVersion,getConfigById,getActiveConfig} from '../src/lib/db/configs';
import {createThread,getThread,saveThreadMessages,getThreadMessages,deleteThread} from '../src/lib/db/threads';
import {getStoredProviderKeys,storeEncryptedKey,listStoredProviders} from '../src/lib/db/api-keys';
import {PostgresGeoStore} from '../src/lib/db/geo-store';
import {getPlanById} from '../src/lib/db/plans';
import {approvePlanToTracker,listTrackerItems,updateTrackerItem} from '../src/lib/db/tracker';
import {createExample} from '../src/lib/server/examples';
import {reserve,markDispatched,settle,releaseUndispatched,markUncertain,acquireCapacity} from '../src/lib/server/usage';
import {registerClient,issueCode,consumeCode,signAccessToken,verifyMcpToken} from '../src/lib/mcp/auth';
import {csrfToken,validCsrf} from '../src/lib/server/security';
const checks:string[]=[];
async function check(name:string,fn:()=>Promise<unknown>|unknown){await fn();checks.push(name);}
async function actor():Promise<Execution>{const ownerId=randomUUID(),sessionId=randomUUID();await query('insert into getcited_users(id,email,password_hash) values($1,$2,$3)',[ownerId,ownerId+'@test.invalid','fixture-not-a-login']);await query('insert into profiles(id,email) values($1,$2)',[ownerId,ownerId+'@test.invalid']);await query("insert into getcited_sessions(id,owner_id,expires_at) values($1,$2,now()+interval '1 day')",[sessionId,ownerId]);return {ownerId,sessionId,operationId:randomUUID(),mode:'live',deadlineMs:Date.now()+120000};}
const input={brandUrl:'https://example.com',brandName:'Synthetic',brandDomains:['example.com'],competitors:['Other'],competitorDomains:['other.example'],queries:['Which synthetic tool fits a small team?'],budgetUsd:400,teamSize:2,timelineWeeks:8,mode:'we_serve'};
const quote={provider:'openai',model:'gpt-4o-mini',kind:'chat',maximumUsd:0.0001,inputBytes:100,maxOutputTokens:64,shared:true};
async function main(){
 const a=await actor(),b=await actor();
 await check('runtime has no DDL TEMP TRUNCATE or table ownership',async()=>{const r=(await query("select has_schema_privilege(current_user,'public','CREATE') c,has_database_privilege(current_user,current_database(),'TEMP') t,has_table_privilege(current_user,'configs','TRUNCATE') x,(select count(*)::int from pg_tables where schemaname='public' and tableowner=current_user) n")).rows[0];assert.deepEqual(r,{c:false,t:false,x:false,n:0});});
 await check('missing execution cannot read a business repository',async()=>{await assert.rejects(()=>getActiveConfig());});
 const ca=await runWithExecution(a,()=>saveConfigVersion(a.ownerId,input)),cb=await runWithExecution(b,()=>saveConfigVersion(b.ownerId,{...input,brandName:'B'}));
 await check('concurrent identities stay isolated across awaits',async()=>{await Promise.all([runWithExecution(a,async()=>{await new Promise(r=>setTimeout(r,15));assert.equal((await getActiveConfig())?.id,ca.id);assert.equal(await getConfigById(cb.id),null);}),runWithExecution(b,async()=>{assert.equal((await getActiveConfig())?.id,cb.id);assert.equal(await getConfigById(ca.id),null);})]);});
 await check('foreign owner cannot write through a repository',()=>runWithExecution(a,()=>assert.rejects(()=>saveConfigVersion(b.ownerId,input))));
 await check('composite FK rejects an owned run with foreign config',async()=>{await assert.rejects(()=>query("insert into runs(user_id,config_id,brand,brand_domains,competitors,panel,status) values($1,$2,'x','{}','{}','{}','running')",[a.ownerId,cb.id]));});
 await check('prepared insert and ordinary save preserve ordinary active config atomically',()=>runWithExecution(a,async()=>{const [prepared,ordinary]=await Promise.all([saveConfigVersion(a.ownerId,{...input,brandName:'Prepared'},true),saveConfigVersion(a.ownerId,{...input,brandName:'Ordinary'})]);assert.equal(prepared.prepared,true);assert.equal((await getActiveConfig())?.id,ordinary.id);assert.equal((await query('select count(*)::int n from configs where user_id=$1 and is_active',[a.ownerId])).rows[0].n,1);}));
 let threadId='';await check('messages are owned and newest saved history is preserved',()=>runWithExecution(a,async()=>{const t=await createThread(a.ownerId,'New thread');threadId=t.id;await saveThreadMessages(a.ownerId,t.id,[{id:'one',role:'user',parts:[{type:'text',text:'Synthetic question'}]},{id:'two',role:'assistant',parts:[{type:'text',text:'Synthetic result'}]}]);assert.equal((await getThreadMessages(t.id))[1].id,'two');}));
 await check('foreign thread read replace and delete all fail',()=>runWithExecution(b,async()=>{assert.equal(await getThread(threadId),null);await assert.rejects(()=>getThreadMessages(threadId));await assert.rejects(()=>saveThreadMessages(b.ownerId,threadId,[]));await assert.rejects(()=>deleteThread(threadId));}));
 await check('delete owned thread safely cascades messages and corrects storage totals',()=>runWithExecution(a,async()=>{const before=(await query('select bytes from getcited_storage_totals where scope=$1',[a.ownerId])).rows[0].bytes;await deleteThread(threadId);assert.equal((await query('select count(*)::int n from thread_messages where thread_id=$1',[threadId])).rows[0].n,0);assert.ok(Number((await query('select bytes from getcited_storage_totals where scope=$1',[a.ownerId])).rows[0].bytes)<Number(before));}));
 await check('encrypted BYOK is private and replacing a key creates no duplicate',async()=>{await runWithExecution(a,async()=>{await storeEncryptedKey(a.ownerId,'openai','synthetic-fixture-key-A');await storeEncryptedKey(a.ownerId,'openai','synthetic-fixture-key-B');assert.equal((await getStoredProviderKeys()).openai,'synthetic-fixture-key-B');assert.deepEqual(await listStoredProviders(),['openai']);});await runWithExecution(b,async()=>assert.equal((await getStoredProviderKeys()).openai,undefined));const r=(await query('select * from api_keys where user_id=$1',[a.ownerId])).rows;assert.equal(r.length,1);assert.ok(!JSON.stringify(r).includes('synthetic-fixture-key'));});
 let sample:Awaited<ReturnType<typeof createExample>>;
 await check('real prepared runner persists report plan thread with zero usage delta',()=>runWithExecution({...a,mode:'mock'},async()=>{const before=(await query('select count(*)::int n from getcited_usage')).rows[0].n;sample=await createExample();assert.equal(sample.prepared,true);const r=await new PostgresGeoStore(a.ownerId).getReport(sample.runId);assert.equal(r?.run.status,'completed');assert.equal(r?.run.prepared,true);assert.equal(r?.answers.length,4);const messages=await getThreadMessages(sample.threadId);const card=messages[1].parts.find(p=>p.type==='tool-run_benchmark') as {output:{sentiment:{score:number|null};total_citations:number}};assert.ok(card.output.sentiment);assert.equal(typeof card.output.total_citations,'number');assert.equal((await query('select count(*)::int n from getcited_usage')).rows[0].n,before);assert.equal((await getActiveConfig())?.brandName,'Ordinary');assert.deepEqual(await createExample(),sample);}));
 await check('older canonical benchmark and plan repair all display fields without changing stored identities or business rows',()=>runWithExecution(a,async()=>{
  const messages=await getThreadMessages(sample.threadId),original=structuredClone(messages);
  const rows=async()=>(await query('select id,message_id,created_at::text from thread_messages where user_id=$1 and thread_id=$2 order by created_at',[a.ownerId,sample.threadId])).rows;
  const identities=await rows(),storedPlan=await getPlanById(sample.planId);
  for(const m of messages)for(const p of m.parts){
   if(p.type==='tool-run_benchmark'&&p.state==='output-available'){const output=p.output as Record<string,unknown>;delete output.sentiment;delete output.your_citation_share;delete output.total_citations;delete output.citation_gap_count;}
   if(p.type==='tool-build_plan'&&p.state==='output-available'){const output=p.output as Record<string,unknown>;for(const key of ['person_hours','spent_usd','spent_hours','roadmap_overview','execution_guidelines'])delete output[key];}
  }
  for(const m of messages)await query('update thread_messages set parts=$3::jsonb where user_id=$1 and thread_id=$2 and message_id=$4',[a.ownerId,sample.threadId,JSON.stringify(m.parts),m.id]);
  assert.deepEqual(await createExample(),sample);
  const restored=await getThreadMessages(sample.threadId);assert.deepEqual(restored,original);assert.deepEqual(await rows(),identities);assert.deepEqual(await getPlanById(sample.planId),storedPlan);
  const output=(restored[1].parts.find(p=>p.type==='tool-build_plan') as {output:{person_hours:number;spent_usd:number;spent_hours:number;roadmap_overview:{kpi_checkpoint:string;due_date:string}[]}}).output;
  assert.equal(output.person_hours,400);assert.equal(output.spent_usd,storedPlan!.tactics.reduce((n,t)=>n+t.costUsd,0));assert.equal(output.spent_hours,storedPlan!.tactics.reduce((n,t)=>n+t.effortHours,0));assert.ok(output.roadmap_overview.every(w=>w.kpi_checkpoint&&/^\d{4}-\d{2}-\d{2}$/.test(w.due_date)));
 }));
 await check('prepared report plan and messages are private and immutable',async()=>{await runWithExecution(b,async()=>{assert.equal(await new PostgresGeoStore(b.ownerId).getReport(sample.runId),null);assert.equal(await getPlanById(sample.planId),null);await assert.rejects(()=>getThreadMessages(sample.threadId));});await runWithExecution(a,async()=>{await assert.rejects(()=>saveThreadMessages(a.ownerId,sample.threadId,[]));await assert.rejects(()=>deleteThread(sample.threadId));});});
 await check('explicit concurrent plan approval uses persisted roadmap once',()=>runWithExecution(a,async()=>{const p=(await getPlanById(sample.planId))!;const r=await Promise.all([approvePlanToTracker(a.ownerId,{...p,roadmap:[]}),approvePlanToTracker(a.ownerId,p)]);assert.equal(r.filter(x=>x.alreadyApproved).length,1);assert.ok((await listTrackerItems(p.id)).length>0);const item=(await listTrackerItems(p.id))[0];await runWithExecution(b,()=>assert.rejects(()=>updateTrackerItem(item.id,{status:'done'})));}));
 await check('session CSRF rejects malformed and different session tokens',()=>{const t=csrfToken(null,a.sessionId);assert.ok(validCsrf(t,a.sessionId));assert.equal(validCsrf(t,b.sessionId),false);assert.equal(validCsrf(t.split('.').slice(0,-1).join('.')+'.'+'é'.repeat(43),a.sessionId),false);});
 await check('quota cap rejects before any ledger mutation',()=>runWithExecution(a,async()=>{const before=(await query('select count(*)::int n from getcited_usage')).rows[0].n;await assert.rejects(()=>reserve({...quote,maximumUsd:0.3}));assert.equal((await query('select count(*)::int n from getcited_usage')).rows[0].n,before);}));
 await check('revocation before dispatch releases reserved capacity without charge',async()=>{const c=await actor();await runWithExecution(c,async()=>{const {id}=await reserve(quote);await query('update getcited_sessions set revoked_at=now() where id=$1',[c.sessionId]);await assert.rejects(()=>markDispatched(id));assert.equal((await query('select status from getcited_usage where id=$1',[id])).rows[0].status,'released');});});
 await check('crashed reserved attempt expires and delayed worker cannot dispatch',()=>runWithExecution(a,async()=>{const old=await reserve(quote);await query("update getcited_usage set deadline_at=now()-interval '1 second' where id=$1",[old.id]);const next=await reserve(quote);assert.equal((await query('select status from getcited_usage where id=$1',[old.id])).rows[0].status,'released');await assert.rejects(()=>markDispatched(old.id));await releaseUndispatched(next.id);}));
 await check('crashed dispatched attempt retains spend but frees capacity and late usage reconciles',()=>runWithExecution(a,async()=>{const old=await reserve(quote);await markDispatched(old.id);await query("update getcited_usage set deadline_at=now()-interval '1 second' where id=$1",[old.id]);const next=await reserve(quote);let r=(await query('select * from getcited_usage where id=$1',[old.id])).rows[0];assert.equal(r.status,'uncertain');assert.equal(Number(r.reserved_usd),quote.maximumUsd);await runWithExecution(b,()=>settle(old.id,{inputTokens:12,outputTokens:3,actualUsd:0.0000036}));assert.equal((await query('select status from getcited_usage where id=$1',[old.id])).rows[0].status,'uncertain');await settle(old.id,{inputTokens:12,outputTokens:3,cachedInputTokens:0,providerModel:'gpt-4o-mini-fixture',actualUsd:0.0000036});r=(await query('select * from getcited_usage where id=$1',[old.id])).rows[0];assert.equal(r.status,'complete');assert.equal(r.provider_model,'gpt-4o-mini-fixture');await releaseUndispatched(next.id);}));
 await check('invalid known usage preserves conservative uncertain reservation',()=>runWithExecution(a,async()=>{const {id}=await reserve(quote);await markDispatched(id);await settle(id,{inputTokens:1,outputTokens:1,cachedInputTokens:2,actualUsd:0});const r=(await query('select status,actual_usd from getcited_usage where id=$1',[id])).rows[0];assert.equal(r.status,'uncertain');assert.equal(r.actual_usd,null);}));
 await check('operation capacity blocks concurrent same owner and releases on completion',()=>runWithExecution(a,async()=>{const release=await acquireCapacity();await assert.rejects(()=>runWithExecution({...a,operationId:randomUUID()},acquireCapacity));await release();await release();const again=await runWithExecution({...a,operationId:randomUUID()},acquireCapacity);await again();}));
 await check('storage quota rejects before authoritative insert and rolls back counters',async()=>{const before=(await query('select bytes from getcited_storage_totals where scope=$1',[a.ownerId])).rows[0].bytes;const count=(await query('select count(*)::int n from threads where user_id=$1',[a.ownerId])).rows[0].n;try{await query('update getcited_storage_totals set bytes=8388600 where scope=$1',[a.ownerId]);await assert.rejects(()=>query("insert into threads(user_id,title) values($1,'over quota')",[a.ownerId]));assert.equal((await query('select count(*)::int n from threads where user_id=$1',[a.ownerId])).rows[0].n,count);assert.equal(Number((await query('select bytes from getcited_storage_totals where scope=$1',[a.ownerId])).rows[0].bytes),8388600);}finally{await query('update getcited_storage_totals set bytes=$2 where scope=$1',[a.ownerId,before]);}});
 await check('MCP PKCE code single use and durable token revokes with its exact session',async()=>{const c=await actor(),client=await registerClient('Local test',['http://127.0.0.1:8999/callback']),verifier='a'.repeat(43),code=await issueCode({clientId:client.clientId,userId:c.ownerId,sessionId:c.sessionId,redirectUri:client.redirectUris[0],codeChallenge:createHash('sha256').update(verifier).digest('base64url'),scopes:['mcp']});await assert.rejects(()=>consumeCode(code,client.clientId,'b'.repeat(43),client.redirectUris[0]));const grant=await consumeCode(code,client.clientId,verifier,client.redirectUris[0]);await assert.rejects(()=>consumeCode(code,client.clientId,verifier,client.redirectUris[0]));const token=await signAccessToken(grant);assert.equal((await verifyMcpToken(token)).userId,c.ownerId);await query('update getcited_sessions set revoked_at=now() where id=$1',[c.sessionId]);await assert.rejects(()=>verifyMcpToken(token));});
 console.log(JSON.stringify({status:'passed',checks,count:checks.length,real_provider_calls:0,ownerA:a.ownerId,ownerB:b.ownerId}));
}
main().catch(e=>{console.log(JSON.stringify({status:'failed',checks,category:e?.name,message:String(e?.message).slice(0,220)}));process.exitCode=1;}).finally(closeDatabase);
